apiVersion: v1
kind: Service
metadata:
  name: springtrader-app
spec:
  selector:
    app: springtrader-app
  ports:
  - name: frontend
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: dblocator
    port: 1527
    protocol: TCP
    targetPort: 1527
  - name: dbserver
    port: 1528
    protocol: TCP
    targetPort: 1528
  type: ClusterIP
